### ISSUE TITLE
mexNormalizeHistogramChar.cpp

### ISSUE THREAD

**Issue by bartoszzielinski** [shamangary/ASV#1]
Is it possible to obtain mexNormalizeHistogramChar.cpp file?
This repository contains only compiled version (mexNormalizeHistogramChar.mexa64) which does not work for Windows and Mac... :/

**Comment by shamangary** [comment]
Hi. The file comes from DSP-SIFT and only DSP-SIFT needs it. I do not actually compile it. Please ask DSP-SIFT author for the file.
